apiVersion: v1
kind: Service
metadata:
  name: maven-cd
spec:
  type: ClusterIP
  selector:
    app: maven-cd
  ports:
    - protocol: TCP
      port: 3000          
      targetPort: 3000  
      containerPort: 3000

