apiVersion: v1
kind: Service
metadata:
  name: maven-cd
spec:
  type: ClusterIP
  selector:
    app: maven-cd
  ports:
    - protocol: TCP
      port: 8080          
      targetPort: 8080  
      containerPort: 8080

